### ISSUE TITLE
Problem z ustawianiem opisu

### ISSUE THREAD

**Issue by Kucharskov** [KsaR99/BotAPI-GG#1]
Hej! Pewnie sie nie spodziewałeś, że ktokolwiek otworzy tutaj "issue" 
Mam problem, ponieważ zawsze używałem dawnej wersji BotAPI. Ostatnio zauważyłem, że wydałeś wersję 3.0, czym prędzej zaktualizowałem swojego bota i wszystko śmigało prócz felernego ustawiania opisu.

Ile ja to sie nie namordowałem jeszcze na wersji 2.0, żeby ta funkcja mi działała i ostatecznie udało mi się. Niestety po aktualizacji do wersji 3.0 ten ficzer nie działa.

Przeglądałem po kolei wersje plików commit po commicie i powiem, że jakaś zmiana w pliku "PushConnection.php" powoduje u mnie błąd, którego w żaden sposób wyłapać nie mogę. Jestem pewien, że to ten plik, ponieważ aktualnie bot mi działa na najnowszym pliku "MessageBuilder.php" z Twojego repo, ale "PushConnection.php" musiałem przywrócić z commita o nazwie "Update © since". Kolejne commity (czyli właśnie owa wersja 3.0) powodują, że bot najpierw po prostu traci możliwość zmiany statusu, a następnie w kolejnych commitach sypie błędem (ten commit o Exception).

Treść błędu:

> Fatal error:  Uncaught Exception: Niepowodzenie ustawiania statusu. in **FOLDER_DO_ggAPI**/PushConnection.php:155Stack trace:#0 **FOLDER_DO_PLIKU_PHP**(85): PushConnection->setStatus('Status systemu:...', 'STATUS_BACK')#1 {main}  thrown in **FOLDER_DO_ggAPI**/PushConnection.php on line 155

Co do mojego systemu na którym to wszystko siedzi:
System: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-93-generic x86_64)
PHP: 7.0.22-0ubuntu0.16.04.1

Nie wiem co jeszcze mogę podać za informacje, aby podpowiedzieć gdzie leży błąd. Chętnie pomogę, bo w sumie samo znalezienie tego repo mnie uratowało w przywróceniu bota do życia. Mogę zapodać dane z całego phpinfo() tylko nie tutaj, żeby ewentualnych danych serwera nie wrzucać.

**Comment by KsaR99** [comment]
Hm u siebie na czacie używam co wiadomość do aktualizacji statusu kto kiedy ostatnio, i działa.

Między 2.5 a 3.0 zostało dodane rzucanie wyjątków w razie niepowodzenia
wcześniej zwracało liczbę ale nie było to udokumentowane więc ten kto nie zajrzał w skrypt nawet by nie wiedział że tu taka opcja istnieję.

Spróbuj zmienić `STATUS_BACK` na `PushConnection::STATUS_BACK` bo zostało to przeniesione do klasy wraz z innymi statusami.
[Tutaj masz jeszcze listę zmian](https://github.com/KsaR99/BotAPI-GG/blob/master/README.md)

ps. polecam także dodać kod do obsługi wyjątków biblioteki.

`try {
    /* kod */
} catch (Exception $e) {
    echo 'Niepowodzenie: ', "\n", $e->getMessage();
} catch (PushConnectionException $e) {
    echo 'Problem po stronie GG: ', "\n", $e->getMessage();
}`

**Comment by Kucharskov** [comment]
No i jednak! Udało się rozwiązać problem. Chodziło właśnie o to, że wcześniej stałe STATUS_* można było bez problemu używać jak to jest napisane w dokumentacji na stronie https://boty.gg.pl/dokumentacja/
Teraz, w wersji 3.0, dostęp do tych stałych wygląda delikatnie inaczej, co sam zaznaczyłeś w liście zmian. Wystarczyło w kodzie bota poprawić na PushConnection::STATUS_*.

Wypadałoby napisać jakiś prosty pomost do tłumaczenia użytych stałych na nowe, bądź uaktualnić dokumentację na stronie GG. Nie wiem co będzie prościej, bo ja niestety do GG dużego dostępu nie mam, a Twoje dzieło jest u nich do pobrania.

Podziwiam, wielka robota! Chętnie zagadnę na GG: 5334195
Pozdrawiam!
